Cox-Automotive/alks-cli

- lib/keys.js
This allows the profile in the ~/.aws/credentials file to retain other keys, such as region, if the credentials-related keys are updated.
> Make updateCreds only overwrite relevant keys, and not the whole INI section.

- README.md
- bin/alks-developer-accounts
- bin/alks-iam-createrole
- bin/alks-sessions-console
- bin/alks-sessions-open
- changelog.txt
- lib/utils.js
- npm-shrinkwrap.json
- package.json
- Export account shortcuts: `eval $(alks developer accounts -e)`
- After exporting you can make simpler calls: `alks sessions open -a "$awsacsnp"`
- Role is now inferred from account for security v2 accounts, so `-r` is optional
> 2.7.0 Release

- README.md
- lib/utils.js
- test/alks.js
We ran into an issue where using alks under docker on windows was returning bash export statements.  By allowing isWindows to sniff an environment we can get SET statements instead.
We may need to loop back later for powershell options, but we don't need it at the moment.
> Pass windows platform to docker

- README.md
- lib/developer.js
- lib/keys.js
Allow server and userid to be set in the environment, so a user can retrieve a set of STS credentials without running `alks developer configure` interactively.
> Environment overrides

- README.md
`https://` portion of the url value was hidden, which is needed for the prompt input. Backtick clears up that `https://` is needed.
> escape hyperlink for ALKS server prompt input

- bin/alks-sessions-console
Using an extension in firefox like this:
https://github.com/honsiorovskyi/open-url-in-container
And its associated shell script:
https://github.com/honsiorovskyi/open-url-in-container/blob/master/launcher.sh
And an alias like this (zsh):
```
function alkssc() {
[ -f ~/.cache/alksda ] && source ~/.cache/alksda || {
alks developer accounts -e | sed 's/export [^=]*-[^=]*=.*//' > ~/.cache/alksda
source ~/.cache/alksda
}
local alks_account
alks_account=${AWS_PROFILE}_admin
if [ ! -v $alks_account ]; then
alks_account=${AWS_PROFILE}_labadmin
fi
local url=$(alks sessions console -i -a "${(P)alks_account}" -u)
~/.dotfiles/bin/firefox-container -n $AWS_PROFILE "$url"
}
```
I am able to open an AWS console in a container tab in Firefox on the command-line:
```
$ AWS_PROFILE=awsmarven alkssc
```
As …
> add -u option to alks session console to just get url

- lib/developer.js
There's a rather critical bug in how we handle ``~/.netrc`` files, used for storing credentials on Linux. ALKS is currently treating netrc like a free-form file, but it's not; netrc files need to conform to a [given format](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) and can only include a specific, small set of tokens: ``machine <name>``, ``login <string>``, ``password <string>``, ``account <string>`` and ``macdef <macro>``.
ALKS is currently setting the ``password`` field for normal username/password credentials, but an invalid ``token <Okta Refresh Token>`` field when using 2FA auth.
This has been breaking Python's built-in netrc module:
```
$ cat ~/.netrc
machine alksclitoken
token MyOktaRefreshTokenWouldGoHere
$ python
Python 3.7.4 (default, Oct …
```
> Fix critical bug in netrc handling on Linux

- bin/alks-developer-login2fa
This will redirect to the new ALKS UI token management page. No longer opening the legacy ALKS refresh token page.
_Note: Should be merged once the legacy ALKS is deprecated and beta ALKS goes **live**!_
Good luck reviewer!
> Token Management Deep Link Fix

- lib/keys.js
- lib/sessions.js
- npm-shrinkwrap.json
This PR fixes a small defect in which a new session & resumed session would return two differently formatted `expires` values. This has been updated, and now they both return `ISO8601` formatted date strings.
Good luck reviewer! 👍
> Normalized "Expires" Output

- lib/keys.js
This PR corrects a report issue were expired keys were mistakenly being returned during `alks sessions open`.
The internal storage format was not properly comparing stored keys versus the current time to determine if they'd expired.  This PR replaces the complex date type with the native JS date type for the purposes of storage and querying to correct the issue.
> Fix expired keys

- changelog.txt
- lib/keys.js
- package.json
[BUGFIX] Corrects an issue where expired keys could be returned by `alks sessions open`.
> Merge develop into master

- lib/keys.js
This PR corrects an issue with the expiration date format of the `aws` output type.  AWS requires a strictly ISO8601 formatted timestamp.  This was not an issue for keys generated for the AWS CLI, but some SDKs do not handle alternative date formats properly and exclude keys with incorrect formatted expiration times.
Here's more information on the expected format: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
```json
{
"Version": 1,
"AccessKeyId": "an AWS access key",
"SecretAccessKey": "your AWS secret access key",
"SessionToken": "the AWS session token for temporary credentials", 
"Expiration": "ISO8601 timestamp when the credentials expire"
} 
```
> Fix expiration format aws

- .travis.yml
- README.md
- package.json
Updates the supported node versions to match those supported by node's own LTS plan (older versions of node may still work with alks-cli but as of this PR we won't officially support or recommend using those older versions)
> bumps the supported node version to 10+

- .github/workflows/check-for-release-tag.yml
- .github/workflows/trigger-release.yml
Patches an injection vulnerability in the trigger-release github action and requires PRs to manually update the contents of changelog.txt rather than automatically updating it from the body of the PR.
> Manual changelog

- .github/workflows/check-for-release-tag.yml
- changelog.txt
- dist/changelog.txt
updates the changelog to reflect changes from PR #202 whose build failed this morning. This PR should trigger the release for that PR's changes
Also fixes the boolean logic for the check that ensures changelog.txt is updated. Before this fix the check would fail regardless of if the changelogs were the same or different
> updates changelog.txt

- .gitattributes
Makes PRs easier to review by hiding diffs for files in the `dist/` folder. Since these files are automatically generated by the build pipeline, there's no need to review them. 
Documentation: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-how-changed-files-appear-on-github
> ignores the dist folder in PR diffs

- .github/workflows/trigger-release.yml
- changelog.txt
- dist/changelog.txt
Fixes the build automation which was previously failing if the date in `changelog.txt` was already today's date, causing there to be nothing to update which caused the pipeline to fail due to the nonzero exit code. Since this bug affected the previous 3 would-be deployments, this PR has been labelled as a release PR so that the following changes will be released:
* adds more CLI options so that some actions can be performed non-interactively in a single line
* fixes support for not saving passwords, giving you the option to enter your password every time
* adds support for configuration using environment variables without needing to run `alks developer configure`
> Fix same day builds

- changelog.txt
- dist/changelog.txt
- dist/package.json
- package.json
- test.Dockerfile
Moves keytar to an option dependency (which it probably should have been before) since it's not necessarily needed for ALKS to run. For instance, if keytar isn't present or fails to load, the ALKS cli is capable of falling back to plaintext files or simply asking for your password each time
> Optional keytar

- dist/package.json
- npm-shrinkwrap.json
- package.json
The following warning was showing up in vscode for line 20 of `src/lib/getCallerInfo.ts`: 
```
This syntax requires an imported helper named '__spreadArray' with 3 parameters, which is not compatible with the one in 'tslib'. Consider upgrading your version of 'tslib'.ts(2807)
```
This PR will not trigger a release
> updates tslib to silence a warning and runs `npm audit fix`

- .github/workflows/code-coverage.yml
- sonar-project.properties
* Fixes code coverage action
Updates the cloudqube WAF ([here](https://ghe.coxautoinc.com/ETS-CloudAutomation/cloudqube/pull/5)) to allow github hosted runner IPs through. Also updates coverage report to distinguish between test and src files.
> updates code coverage action
