Cox-Automotive/alks-cli

- README.md
- bin/alks-developer-configure
- bin/alks-developer-login
- lib/account.js
- lib/utils.js
- package.json
> Replacing key tar with Clortho..

- bin/alks-keys-create
- lib/utils.js
- package.json
You'll need to have git installed until our PR is merged.
> Switching to custom fork of clortho

- README.md
- bin/alks-sessions-open
- changelog.txt
- package.json
Adds `-N` argument to `alks sessions open`, this will force new session.
> 2.1.1 Patch Release

- bin/alks-developer-configure
- bin/alks-sessions-list
- changelog.txt
- lib/developer.js
- npm-shrinkwrap.json
- package.json
- Fix for issue running configure with only IAM accounts
- Fix for list sessions reporting no active sessions
> 2.6.1 Patch Release

- bin/alks-developer-accounts
- changelog.txt
- lib/developer.js
- lib/utils.js
- npm-shrinkwrap.json
- package.json
- Adds account export support for Windows
- Code cleanup
> 2.7.2 Patch Release

- README.md
- bin/alks-developer-accounts
- bin/alks-developer-configure
- bin/alks-iam-createrole
- bin/alks-sessions-console
- bin/alks-sessions-open
- changelog.txt
- lib/developer.js
- lib/iam.js
- npm-shrinkwrap.json
- package.json
Better aligns the CLI with the website. You can now see your Admin and IAMAdmin accounts when doing `alks sessions open`. Note you'll still need to pass the `-i` argument to start an IAM/Admin session.
> 2.9.0 Release

- bin/alks-iam
- bin/alks-iam-createrole
- bin/alks-iam-delete
- bin/alks-iam-deleterole
- changelog.txt
- npm-shrinkwrap.json
- package.json
Adds support for deleting IAM roles. Also includes misc cleanups and optimizations.
> 2.10.0 Release

- README.md
- bin/alks-iam-createrole
- changelog.txt
- lib/utils.js
- npm-shrinkwrap.json
- package.json
- test/alks.js
- Updates ALKS library
- Enhanced error messaging
- Now displays IP ARN where applicable 
- Windows Docker improvements
> 2.10.2 Release

- bin/alks-developer
- bin/alks-developer-favorites
- bin/alks-sessions-open
- changelog.txt
- lib/developer.js
- lib/iam.js
- lib/sessions.js
- npm-shrinkwrap.json
- package.json
→ You can now set favorite accounts: `alks developer favorites`
→ `alks sessions open` now floats your favorites to the top
→ `alks sessions open` now supports `-F` to filter your favorites
> ALKS 2.11.0

- README.md
- bin/alks-developer-configure
- bin/alks-developer-info
- bin/alks-server-start
- bin/alks-sessions-open
- changelog.txt
- lib/developer.js
- lib/keys.js
- lib/sessions.js
- lib/utils.js
- npm-shrinkwrap.json
- package.json
> Output defaults and PowerShell support

- README.md
Updating the createltk section, based on our conversation earlier: Clarifying 'Required' vs 'Optional' params, and removing -p.
> Update createltk section of README

- README.md
- changelog.txt
- lib/developer.js
- lib/keys.js
- npm-shrinkwrap.json
- package.json
→ Support for running without configuring (supply `$ALKS_SERVER` & `$ALKS_USERID`)
→ Fix for missing AWS credentials file
> 2.16.0 Release

- README.md
- bin/alks-iam
- bin/alks-iam-createtrustrole
- npm-shrinkwrap.json
- package.json
* Updated `README.md`
* Updated `bin/alks-iam` to add `createtrustrole`
* Added `bin/alks-iam-createtrustrole`
* Updated `package.json` to use latest `alks-node`
* Updated `npm-shrinkwrap.json` using  `npm shrinkwrap` command
> Trust Role support

- lib/iam.js
- lib/sessions.js
- npm-shrinkwrap.json
- package.json
updates the way sessions.js and iam.js fetch new keys from ALKS by having them request the max key duration for a role via the updated method added to alks-node by this PR https://github.com/Cox-Automotive/alks-node/pull/4
> Support max key duration

- changelog.txt
- package.json
Updates version and adds change log notes.
> Updates version and change log

- changelog.txt
- package.json
This PR bumps the package version and updates the CLI changelog file.
> Updates version and changelog

- changelog.txt
- package.json
bumps version and updates change log
> bumps version number

- npm-shrinkwrap.json
- package.json
Lists `clortho` dependency as a tarball to revert potentially breaking changes introduced in v3.0.6
> Clortho tarball

- README.md
This PR updates the docs by including some documentation on the `-u` and `-o` commands for ALKS CLI. Went through the codebase and matched any missing arguments into the `README.md` file.
Good luck reviewer! 👍
> Updated README Docs

- lib/iam.js
This PR corrects a small bug with IAM key generation and calculation of key expiration.
> [BUGFIX] Corrects issue with IAM Key expirations

- changelog.txt
- lib/iam.js
- package.json
Merge recent changes from `develop` to `master`.  These changes include:
- Fix a bug with IAM key generation and expiration timestamps
> Merge develop to master

- npm-shrinkwrap.json
- package.json
Updates `alks-node` dependency to the latest version.
> Bump alks-node

- bin/alks-iam-createrole
- bin/alks-iam-createtrustrole
- npm-shrinkwrap.json
- package.json
This fixes a bug where when we create roles we're not passing the attribute to allow a role to be a MI.
> [BUGFIX] Allow support for MI.

- bin/alks
- bin/alks-developer
- bin/alks-developer-accounts
- bin/alks-developer-configure
- bin/alks-developer-favorites
- bin/alks-developer-info
- bin/alks-developer-login
- bin/alks-developer-login2fa
- bin/alks-developer-logout
- bin/alks-developer-logout2fa
- bin/alks-iam
- bin/alks-iam-createltk
- bin/alks-iam-createrole
- bin/alks-iam-createtrustrole
- bin/alks-iam-deleteltk
- bin/alks-iam-deleterole
- bin/alks-iam-roletypes
- bin/alks-server
- bin/alks-server-configure
- bin/alks-server-start
- bin/alks-server-stop
- bin/alks-sessions
- bin/alks-sessions-console
- bin/alks-sessions-list
- bin/alks-sessions-open
- npm-shrinkwrap.json
- package.json
This PR builds on alks-node PR where we basically updated all the errors to be properly extracted on ALKS calls. Also went ahead and updated syntax and everything to keep CLI up to date. Tested locally through a call in every file and no problems seem to come up :)
> [IP] Fix Error Handling & Update Syntax

- changelog.txt
This updates the `changelog.txt` to be more explicit on the changes made in previous PR.
> Fixed ChangeLog

- changelog.txt
- package.json
> Updates release details

- .travis.yml
> Retire Travis CI

- .github/workflows/node.js.yml
- .github/workflows/trigger-release.yml
Creates a github action to automate the creation of a release and deployment to NPM
> adds github actions for automatically building/deploying the CLI

- .github/workflows/trigger-release.yml
* Creates a github action to automate the creation of a release and deployment to NPM
> makes github action force push to avoid branch protections

- .github/workflows/build-and-test.yml
- .github/workflows/trigger-release.yml
- changelog.txt
- dist/changelog.txt
Fixes github actions and should automatically deploy a new version of the CLI that includes changes from the following already-merged PRs: #216 #217 #218
> Fix GitHub actions

- Dockerfile
Not sure if this will automatically update [this page](https://hub.docker.com/r/coxauto/alks-cli) but I'm hoping it will
> updates dockerfile

- changelog.txt
- e2e/test.bats
- src/lib/handlers/alks-developer-accounts.ts
* Alters account JSON output to be an object indexed by accountId 
Moving from a 2D Array to the following:
```
{
"955007298069": {
"accountAlias": "awsxtimemcp",
"roles": [
{
"role": "Security",
"isIamActive": false
},
{
"role": "Admin",
"isIamActive": true
}
]
},
"085685109815": {
"accountAlias": "awsxtimemcpnp",
"roles": [
{
"role": "Security",
"isIamActive": false
}
]
}
}
```
> Adds clarity to JSON output

- changelog.txt
- dist/changelog.txt
This is an empty PR to force a rerun of a failed github actions workflow
> empty commit to trigger release
